
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[tests]
before_script:
  - flake8 .
script:
  - nosetests -v --cover-erase --with-coverage --cover-package=novaagent
